---
title: "So Many Ads, So Many Themes"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(highcharter)
library(gapminder)
library(htmlwidgets)
library(kableExtra)
library(fmsb)
library(plotly)
```

```{r upload files, echo=FALSE, message=FALSE}
data_ad_time <- read_csv("~/STA 518/Final Project/Portfolio/Final Proposal/Final Project/Ad  Time _ Category - Sheet1.csv")
data <- read_csv("~/STA 518/Final Project/Portfolio/Final Proposal/Final Project/combined  - Sheet1.csv")
data_ad_cost <- read_csv("~/STA 518/Final Project/Portfolio/Final Proposal/Final Project/Cost per Super bowl ad 2000-2020 - Sheet1 (1).csv")
```
```{r joining two data sets, echo=FALSE, message=FALSE, results="hide"}
# merge data and data_ad_cost together 
total <- inner_join(data, data_ad_cost, by="year")
total
dim(total)
knitr::kable(total)
#chr to Numeric cost_per_minute and cost_per_thirty_seconds
total11<-
total%>% as.data.frame %>%
  mutate(cost_per_minute=str_remove_all(cost_per_minute,"[$,]"),
         cost_per_minute=as.numeric(cost_per_minute)) %>%
  mutate(cost_per_thirty_seconds=str_remove_all(cost_per_thirty_seconds,"[$,]"),
        cost_per_thirty_seconds=as.numeric(cost_per_thirty_seconds))%>%
  
  mutate(cost_per_second = cost_per_minute/60 )%>%
  
  mutate(cost_of_ad= cost_per_second*ad_time) %>%
  mutate(cost_of_ad_in_millions =cost_of_ad/1000000 )%>%
  mutate(cost_per_second_in_thousands =cost_per_second/100000)
  
total11
 # mutate(currency = scales::dollar(cost_per_second))
  
 
  
```

```{r exploratory bar charts, echo=FALSE, message=FALSE}
# count of brands use of gender
ggplot(data=total, aes(x=category)) +
  geom_bar(stat= "count", position="dodge",color= "black", aes(fill=celebrity))+ 
   ggtitle("Bar char of Super Bowl Ad Categories and Celebrity Apperances From 2000-2020")
```

```{r porportions, echo=FALSE, message=FALSE}
 ggplot(data=total11, aes(x= year, fill=use_sex))+
   geom_bar(stat= "count", position="fill")+
   ggtitle("Porportion of SuperBowl Ads that use Sex Appeal from 2000 to 2020")
```

```{r ad_themes, echo=FALSE, message=FALSE}
#creating frequency table 
 
total11 %>%
  group_by(ad_time) %>%
  summarize(Frequency=n()) %>%
  arrange(desc(Frequency)) %>%
  mutate(Proportion=Frequency/sum(Frequency)) %>%
  mutate(AdTime= ad_time)%>%
  select(AdTime, Frequency, Proportion)%>%
  print(n=50)
```
  
#Frequency table of Diverse Ads vs Year
```{r diverse, echo=FALSE, message=FALSE}  
total11 %>%
  group_by(diversity, year) %>%
  summarize(Frequency=n()) %>%
  arrange(year) %>%
  mutate(Proportion=Frequency/sum(Frequency))%>%
    mutate(Year=year)%>%
  select(Year,diversity, Frequency, Proportion,-year)%>%
  print(n=50)
```

#pie chart of animal use 
```{rpercentage, echo=FALSE, message=FALSE}
 total12<- total11 %>%
  group_by(animals) %>%
  summarise(counts=n(),
            percentage= n()/nrow(total11))
 #pie chart
 ggplot(data=total12, aes(x="", y=percentage, fill=animals))+
  geom_col(color="blue")+
  coord_polar("y", start=0)+
  geom_text(aes(label= paste0(round(percentage*100), "% ")),
            position = position_stack(vjust = 0.5))+
  theme(panel.background = element_blank(),
        axis.line= element_blank(),
         axis.text= element_blank(),
         axis.ticks= element_blank(),
        plot.title=element_text(hjust=0.5, size=18))+
  ggtitle("Pie Chat of Percentage of Ads that use Animals")+
   scale_fill_brewer("Use Animals")

```