---
title: "STA 518 Final Project"
description: |
  In our final project, we will investigate superbowl ads from 2000 to 2020 using a data set from Five Thirty Eight. We will make a website or application that displays trends of brands’ advertisement strategies over time and use predictive modeling/ simulations to anticipate which direction superbowl ads will go in the future. Here is our link to the Main dataset (https://github.com/fivethirtyeight/superbowl-ads/blob/main/superbowl-ads.csv) and here is the link to the cost per second for ad (https://www.sportingnews.com/us/nfl/news/super-bowl-commercials-cost-2022/v9ytfqzx74pjrcdvxyhevlzd)


site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

library(tidyverse)
library(highcharter)
library(gapminder)
library(htmlwidgets)
library(kableExtra)
library(fmsb)
library(plotly)

```


```{r upload files}
data_ad_time <- read_csv("Ad  Time _ Category - Sheet1.csv")
data <- read_csv("combined  - Sheet1.csv")
data_ad_cost <- read_csv("Cost per Super bowl ad 2000-2020 - Sheet1 (1).csv")
```

```{r joining two data sets, echo=FALSE, results=FALSE }
# merge data and data_ad_cost together 
total <- inner_join(data, data_ad_cost, by="year")
total
dim(total)
#chr to Numeric cost_per_minute and cost_per_thirty_seconds
total11<-
total%>% as.data.frame %>%
  mutate(cost_per_minute=str_remove_all(cost_per_minute,"[$,]"),
         cost_per_minute=as.numeric(cost_per_minute)) %>%
  mutate(cost_per_thirty_seconds=str_remove_all(cost_per_thirty_seconds,"[$,]"),
        cost_per_thirty_seconds=as.numeric(cost_per_thirty_seconds))%>%
  
  mutate(cost_per_second = cost_per_minute/60 )%>%
  
  mutate(cost_of_ad= cost_per_second*ad_time) %>%
  mutate(cost_of_ad_in_millions =cost_of_ad/1000000 )%>%
  mutate(cost_per_second_in_thousands =cost_per_second/100000)
  
total11
 # mutate(currency = scales::dollar(cost_per_second))
  
 
  
```
```{r }
#total1<- bind_cols(data_ad, data_ad_time %>% select(-year, -brand))
```


```{r exploratory bar charts, echo=FALSE}
# count of brands use of gender
ggplot(data=total, aes(x=category)) +
  geom_bar(stat= "count", position="dodge",color= "black", aes(fill=celebrity))+ 
   ggtitle("Bar char of Super Bowl Ad Categories and Celebrity Apperances From 2000-2020")
```
```{r line graph, echo=FALSE, results=FALSE}
  ggplot(data=total11, aes(cost_per_second)) +
  geom_histogram(binwidth = 10)
  
  #line graph
  ggplot(data=total11, aes(x=year, y=cost_per_second_in_thousands)) +
  geom_line(linetype = "dashed", color="blue", size=1)+
    theme(legend.position="bottom")+
  geom_point(color="blue")+
  ggtitle("Cost Per Second of Super Bowl Ads from 2000 to 2020")+
    ylab("Cost (Hundreds of Thousands of Dollars)")
  
  
  
  #histogram of distribtuion of cost_of_ad by Year
  
total11 %>%
  group_by(year)
  ggplot(data=total11, aes(y=year, fill=year, color=year)) +
  geom_histogram(alpha=0.5, position="dodge", bins=10)+
       scale_color_brewer(palette="") + 
  theme_classic()+theme(legend.position="top")
 
  
  ggplot(data=total, aes(x=year)) +
  geom_bar( stat="count", position="dodge",colour="black", aes(fill=diversity)) 
  
```
```{r porportions, echo=FALSE}
 ggplot(data=total11, aes(x= year, fill=use_sex))+
   geom_bar(stat= "count", position="fill")+
   ggtitle("Porportion of SuperBowl Ads that use Sex Appeal from 2000 to 2020")
```

```{r boxplot, reorder, echo=FALSE }
#reordering boxplots based on median cost_of_ad
ggplot(data=total11, aes(x= fct_reorder(category, cost_of_ad_in_millions), y=cost_of_ad_in_millions))+
geom_boxplot(fill="lightblue")+
ggtitle("Boxplots of Cost Per Ad by Category")+
xlab("Ad Category")+
ylab("Ad Cost in Millions")
```

sunburst Plot of total Ad Cost
 
```{r sunburst, echo=FALSE}
total3 <- data_to_hierarchical(data=total11, c(category, brand),cost_of_ad_in_millions)


hchart(total3, type = "sunburst")%>%
hc_title(text="Total Ad Cost by Category and Brand in Millions from 2000-2020")

hchart(total3, type = "treemap")



#bubble plot
p<- ggplot(data=total11, aes(x=year, y=cost_of_ad_in_millions, size= use_sex, fill= category))+
  geom_point(alpha=0.5, shape=21, color="black")+
  ylab("Cost of Ad in Millions")+
  xlab("Year")+
  ggtitle("Ad Cost by Year and Category")
  
 ggplotly(p, tooltip="text")

```